### PR TITLE
[DO NOT MERGE] Silee2/install script

### PR DESCRIPTION
**Pull request by silee2**
- Add a script that installs neon with nGraph and aeon into virtualenvs
- Add enum34 as a requirement. Python2 needs it.  (@raramer01 BOM needs to be updated)
- Remove print difference between py2 and py3 for command line args.

### CODE REVIEW

**Comment by silee2** [comment]
TESTNOW

**Comment by silee2** [comment]
TESTNOW

**Comment by raramer01** [comment]
TESTNOW

**Comment by silee2** [comment]
TESTNOW

**Comment by raramer01** [comment]
TESTNOW

**Pull request closed without merging**
